
package presentacion;

import java.awt.Canvas;
import javax.swing.JButton;


public class VistaPrincipal extends javax.swing.JFrame {

    private Modelo modelo;
    private ControladorPrincipal control;
    
    public VistaPrincipal(Modelo m) {
        modelo = m;
        initComponents();
        asignarEventos();
    }

    public Modelo getModelo() {
        return modelo;
    }

    public ControladorPrincipal getControl() {
        if(control == null){
            control = new ControladorPrincipal(this);
        }
        return control;
    }

    public Canvas getLienzo() {
        return lienzo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lienzo);
        lienzo.setBounds(20, 50, 380, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas lienzo;
    // End of variables declaration//GEN-END:variables

    private void asignarEventos() {
        
    }
}
